site_name: relational-datasets
site_description: "A small library for loading and downloading relational datasets."
repo_name: "hayesall/relational-datasets"
site_url: "https://srlearn.github.io/relational-datasets/"
repo_url: https://github.com/hayesall/relational-datasets/
edit_uri: "blob/main/docs/"


theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  features:
    - navigation.instant
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.snippets

plugins:
  - search
  - mkdocstrings:
      watch:
        - relational_datasets
        - README.md
  - git-revision-date-localized
  - awesome-pages
  - mkdocs-jupyter

nav:
  - Home: index.md
  - API Docs:
    - request.load: api/request.load.md
    - request.fetch: api/request.fetch.md
    - types.RelationalDataset: api/relationaldataset.md
  - Downloads: downloads.md
  - ... | dataset_descriptions/*.md
  - Notebooks:
    - "Fetching": notebooks/00_loading_and_fetching.ipynb
  - Changelog: changelog.md
